import { Telegraf } from 'telegraf';
import { AlphaContext } from '../types';
import { registerAdminCommand } from './admin.command';
import { registerAlertsCommand } from './alerts.command';
import { registerAnalyzeCommand } from './analyze.command';
import { registerHelpCommand } from './help.command';
import { registerPriceCommand } from './price.command';
import { registerReferCommand } from './refer.command';
import { registerSettingsCommand } from './settings.command';
import { registerStartCommand } from './start.command';
import { registerStatsCommand } from './stats.command';
import { registerTrackCommand } from './track.command';
import { registerTrendingCommand } from './trending.command';
import { registerUntrackCommand } from './untrack.command';
import { registerUpgradeCommand } from './upgrade.command';
import { registerWalletsCommand } from './wallets.command';
import { registerSuggestCommand } from './suggest.command';
import { registerRedeemCommand } from './redeem.command';
import { registerWhalesCommand } from './whales.command';
import { registerDashboardCommand } from './dashboard.command';
import { registerAppCommand } from './app.command';
import { registerDailyCommand } from './daily.command';

export function registerCommands(bot: Telegraf<AlphaContext>) {
  registerStartCommand(bot);
  registerHelpCommand(bot);
  registerTrackCommand(bot);
  registerUntrackCommand(bot);
  registerWalletsCommand(bot);
  registerSuggestCommand(bot);
  registerPriceCommand(bot);
  registerTrendingCommand(bot);
  registerAnalyzeCommand(bot);
  registerUpgradeCommand(bot);
  registerReferCommand(bot);
  registerSettingsCommand(bot);
  registerAlertsCommand(bot);
  registerRedeemCommand(bot);
  registerWhalesCommand(bot);
  registerDashboardCommand(bot);
  registerAppCommand(bot);
  registerDailyCommand(bot);
  registerStatsCommand(bot);
  registerAdminCommand(bot);
}
